# Generated by Django 3.1.1 on 2020-09-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200402_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answer',
            field=models.CharField(default='No Answer', max_length=200),
            preserve_default=False,
        ),
    ]
